CREATE VIEW v_flight
AS
 SELECT AIRLINES.NAME,FLIGHT_NUMBER,COUNT(CUSTOMER_ID) AS PASSENGERS
 FROM AIRLINES JOIN BOOKINGS ON AIRLINES.CODE=AIRLINE_CODE
 WHERE STATUS=1
 GROUP BY AIRLINES.NAME,FLIGHT_NUMBER;
 
 
CREATE VIEW v_agency
AS
 SELECT CUSTOMERS.FNAME
 FROM CUSTOMERS JOIN BOOKINGS ON ID=CUSTOMER_ID
 GROUP BY AGENCY,CUSTOMERS.FNAME
 HAVING COUNT(CUSTOMER_ID)>=ALL(SELECT COUNT(CUSTOMER_ID)
 FROM CUSTOMERS JOIN BOOKINGS ON ID=CUSTOMER_ID
 GROUP BY AGENCY,CUSTOMERS.FNAME);

CREATE VIEW v_SF_Agencies
AS
 SELECT *
 FROM AGENCIES
 WHERE CITY='Sofia'
WITH CHECK OPTION;

CREATE VIEW v_SF_PH_Agencies
AS
 SELECT *
 FROM AGENCIES
 WHERE PHONE IS NULL
WITH CHECK OPTION;


