CREATE VIEW RichExec
AS
 SELECT NAME,ADDRESS,CERT#,NETWORTH
 FROM MOVIEEXEC
 WHERE NETWORTH>=10000000;
 
 CREATE VIEW Executivestar
 AS
  SELECT MOVIESTAR.NAME,MOVIESTAR.ADDRESS,GENDER,BIRTHDATE,CERT#,NETWORTH
  FROM MOVIESTAR JOIN MOVIEEXEC ON MOVIESTAR.NAME=MOVIEEXEC.NAME;
 
 SELECT NAME
 FROM Executivestar
 WHERE GENDER='F';
 
 SELECT RichExec.NAME
 FROM RichExec JOIN STUDIO ON CERT#=PRESC#;
 
 SELECT NAME
 FROM Executivestar
 WHERE NETWORTH>50000000;
 
 DROP VIEW RichExec;
 
 DROP VIEW Executivestar;
 