CREATE INDEX index_classes
ON CLASSES( CLASS,TYPE,COUNTRY,NUMGUNS,BORE,DISPLACEMENT);

CREATE INDEX index_ships
ON SHIPS(NAME,CLASS,LAUNCHED);

CREATE INDEX index_battles
ON BATTLES(NAME,DATE);

CREATE INDEX index_outcomes
ON OUTCOMES(SHIP,BATTLE,RESULT);

DROP INDEX CLASSES.index_classes;

DROP INDEX SHIPS.index_ships;

DROP INDEX BATTLES.index_battles;

DROP INDEX OUTCOMES.index_outcomes;
