SELECT MAKER, SPEED
FROM LAPTOP JOIN PRODUCT ON LAPTOP.model = PRODUCT.model
WHERE HD > 9;

SELECT PRODUCT.MODEL, PRICE
FROM PRODUCT JOIN PC ON product.model = pc.model
WHERE MAKER='B'
union
SELECT PRODUCT.MODEL, PRICE
FROM product JOIN LAPTOP ON PRODUCT.MODEL= LAPTOP.MODEL
WHERE MAKER='B'
union
SELECT PRODUCT.MODEL, PRICE
FROM PRODUCT JOIN PRINTER ON PRODUCT.MODEL = printer.MODEL
WHERE MAKER='B'

SELECT DISTINCT pc1.HD
FROM PC pc1, PC pc2
WHERE pc1.HD = pc2.HD AND pc1.CODE<> pc2.CODE;

SELECT pc1.MODEL, pc2.MODEL
FROM PC pc1, PC pc2  
WHERE pc1.SPEED = pc2.SPEED  AND  pc1.RAM = pc2.RAM AND pc1.MODEL < pc2.MODEL

SELECT DISTINCT p1.MAKER
FROM PC pc1
JOIN PRODUCT p1 ON pc1.MODEL=p1.MODEL
JOIN PRODUCT p2 on p1.MAKER=p2.MAKER
JOIN PC pc2 on pc2.MODEL=p2.MODEL
WHERE pc1.CODE <> pc2.CODE AND pc1.SPEED> 400 AND  pc2.SPEED> 400;