SELECT MAKER
FROM PRODUCT
WHERE MODEL in (
SELECT MODEl 
FROM PC
WHERE SPEED > 500);

SELECT CODE,MODEL,PRICE
FROM PRINTER
WHERE PRICE>=ALL(
SELECT PRICE
FROM PRINTER);

SELECT*
FROM LAPTOP
WHERE SPEED<ALL(
SELECT SPEED
FROM PC);

SELECT MODEL,PRICE
FROM  (SELECT MODEL,PRICE
FROM PRINTER
WHERE PRICE >= ALL(SELECT PRICE FROM PRINTER)
union
SELECT MODEL,PRICE
FROM PC
WHERE PRICE >= ALL(SELECT PRICE FROM PC)
union
SELECT MODEL,PRICE
FROM LAPTOP
WHERE PRICE >= ALL(SELECT PRICE FROM LAPTOP)) t
WHERE t. PRICE >= ALL (SELECT PRICE FROM
(SELECT MODEL,PRICE
FROM PRINTER
WHERE PRICE >= ALL(SELECT PRICE FROM PRINTER)
union
SELECT MODEL,PRICE
FROM PC
WHERE PRICE >= ALL(SELECT PRICE FROM PC)
union
SELECT MODEL, PRICE
FROM LAPTOP
WHERE PRICE>= ALL(SELECT PRICE FROM LAPTOP)) t);

SELECT MAKER
FROM PRODUCT
WHERE MODEL in
(SELECT MODEL
FROM PRINTER
WHERE COLOR='y' AND PRICE <= ALL(SELECT PRICE FROM PRINTER WHERE COLOR='y'));

SELECT MAKER
FROM PRODUCT
WHERE MODEL in (
SELECT MODEL
FROM PC p
WHERE RAM <= ALL (
SELECT RAM
FROM PC ) AND SPEED>= ALL(
SELECT SPEED
FROM PC 
WHERE RAM=p.RAM));

