SELECT DISTINCT COUNTRY
FROM CLASSES
WHERE NUMGUNS>=ALL(
SELECT NUMGUNS
FROM CLASSES);

SELECT DISTINCT CLASS 
FROM SHIPS
WHERE NAME=ANY(
SELECT SHIP
FROM OUTCOMES
WHERE RESULT='sunk');

SELECT NAME,CLASS
FROM SHIPS
WHERE CLASS in(
SELECT CLASS
FROM CLASSES
WHERE BORE=16
);

SELECT BATTLE
FROM OUTCOMES
WHERE SHIP in(
SELECT NAME
FROM SHIPS
WHERE CLASS='KONGO');


SELECT c1. CLASS, NAME
FROM CLASSES c1, SHIPS s
WHERE NUMGUNS >= ALL 
(SELECT NUMGUNS 
FROM CLASSES
WHERE BORE=c1.BORE)
AND s.CLASS = c1.CLASS 
order by c1.class; /**/
