ALTER TABLE FLIGHTS
ADD num_pass INT;

ALTER TABLE AGENCIES
ADD num_book INT;

CREATE TRIGGER tr_insert_res 
ON BOOKINGS
AFTER INSERT 
AS
 UPDATE FLIGHTS
 SET NUM_PASS=NUM_PASS+1
 UPDATE AGENCIES
 SET NUM_BOOK=NUM_BOOK+1;

 CREATE TRIGGER tr_del_res 
 ON BOOKINGS
 AFTER DELETE
 AS
  UPDATE FLIGHTS
  SET NUM_PASS=NUM_PASS-1
  UPDATE AGENCIES
  SET NUM_BOOK=NUM_BOOK-1;

CREATE TRIGGER tr_update_res 
ON BOOKINGS
AFTER UPDATE
AS
 UPDATE FLIGHTS
 SET NUM_PASS=NUM_PASS-1
 WHERE FNUMBER IN(SELECT FLIGHT_NUMBER
					 FROM deleted);
 UPDATE FLIGHTS
 SET NUM_PASS=NUM_PASS+1
 WHERE FNUMBER IN(SELECT FLIGHT_NUMBER
					 FROM inserted);
 UPDATE AGENCIES
 SET NUM_BOOK=NUM_BOOK-1
 WHERE NAME IN(SELECT AGENCY
			   FROM deleted);
 UPDATE AGENCIES
 SET NUM_BOOK=NUM_BOOK+1
 WHERE NAME IN(SELECT AGENCY
			   FROM inserted);
;
